name: Build, Publish Docker image, and deploy

on:
  workflow_dispatch:
    inputs:
      build:
        description: "Build and Push?"
        required: true
        default: true
        type: boolean
      deploy:
        description: "Deploy?"
        required: true
        default: false
        type: boolean

jobs:
  build_server:
    name: Build server docker and push.
    runs-on: ubuntu-latest
    if: ${{ inputs.build }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get git commit date
        id: date
        run: |
          echo "commit_date=$(git show -s --format=%cd --date=format:%Y%m%d-%H%M%S ${GITHUB_SHA})" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Server - Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production
            IDENTIFY_VERSION_KEY=${{ github.sha }}
          push: true
          tags: |
            ntshav/texas-poker-game:api-latest
            ntshav/texas-poker-game:api-${{ github.event.release.tag_name || env.commit_date }}

  build_client:
    name: Build client docker and push.
    runs-on: ubuntu-latest
    if: ${{ inputs.build }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get git commit date
        id: date
        run: |
          echo "commit_date=$(git show -s --format=%cd --date=format:%Y%m%d-%H%M%S ${GITHUB_SHA})" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Client - Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production
            VUE_APP_API_IP=${{ vars.VUE_APP_API_IP }}
            VUE_APP_API_PORT=${{ vars.VUE_APP_API_PORT }}
            IDENTIFY_VERSION_KEY=${{ github.sha }}
          push: true
          tags: |
            ntshav/texas-poker-game:nginx-latest
            ntshav/texas-poker-game:nginx-${{ github.event.release.tag_name || env.commit_date }}

  deploy:
    name: Deploy To Server
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ !cancelled() }}
    needs: [build_server, build_client]
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        if: ${{ inputs.deploy }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 30m
          command_timeout: 30m
          script: |
            cd ${{ secrets.SSH_WORK_DIR }} && make pull && make start
